/*=======================================================
			CUSTOMER BEHAVIOR ANALYSIS 
=======================================================*/
USE customer_behavior
GO 

--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
	gender, 
	SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
GO

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
	customer_id, 
	purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
	AND 
	  purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
GO

--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
	item_purchased, 
	ROUND(AVG(review_rating),2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
GO

--Q4. Compare the average purchase amounts between Standard and Express Shipping
SELECT 
	shipping_type,
	ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type
GO 


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers 
-- and non-subscribers
SELECT 
	CASE WHEN subscription_status = 'Yes' THEN 'subscriber' ELSE 'non-subscriber' End AS subscription_status, 
	COUNT(*) AS count_customer,
	ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2) avg_purchase_amount, 
	SUM(CAST(purchase_amount AS FLOAT)) total_revenue
FROM customer
GROUP BY subscription_status
GO


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- we are trying to see which product rely heavily on discount to sell

SELECT TOP 5
	item_purchased, 
	ROUND(sum(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) / CAST(COUNT(*) AS FLOAT) * 100, 2) discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
GO

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases
-- and show the count of each segment. 
WITH customer_group AS (
	SELECT 
		customer_id, 
		previous_purchases,
		CASE WHEN previous_purchases = 1 THEN 'New' 
				WHEN previous_purchases >=2 AND previous_purchases <= 10  THEN 'Returning'
				WHEN previous_purchases > 10 THEN 'Loyal'
		END  AS customer_segment
	FROM customer
)
SELECT 
	customer_segment, 
	COUNT(*) count_customer
FROM customer_group
GROUP BY customer_segment
GO


--Q8. What are the top 3 most purchased products within each category? 
WITH product_category AS 
(
	SELECT 
		category, 
		item_purchased, 
		count(customer_id) AS count_purchases,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) rank_product 
	FROM customer	
	GROUP BY CATEGORY, item_purchased
)
SELECT 
	category, 
	item_purchased, 
	count_purchases
FROM product_category
WHERE rank_product <= 3;
GO

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
	CASE WHEN subscription_status='Yes' THEN 'Subcribers' ELSE 'Non-Subcribers' END subscription_status, 
	COUNT(*) repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group?

SELECT 
	age_group, 
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;